# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SprSims < Formula
  desc "Stacked Pull Requests on GitHub"
  homepage "https://github.com/MichaelSims/spr"
  version "2.0.0-sims"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MichaelSims/spr/releases/download/v2.0.0-sims/spr_macos_x86_64.tar.gz"
      sha256 "31c6486249f04d4df1c7e30b83bfd9b9f20912e5f9518958153c4fb4df814af0"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MichaelSims/spr/releases/download/v2.0.0-sims/spr_macos_arm64.tar.gz"
      sha256 "12257399e3fe23c3db13571a70518488d14d948db544343e4112bf8230d2106c"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MichaelSims/spr/releases/download/v2.0.0-sims/spr_linux_arm64.tar.gz"
      sha256 "f5865fccfe80a12abee0476f49bec4004cc352f1f2966baaba95d5be00fa7736"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/MichaelSims/spr/releases/download/v2.0.0-sims/spr_linux_x86_64.tar.gz"
      sha256 "41045c433d73d57b5872f1bb307abf5ea4d9e1147e0c9e914145e9a1fa9af9f7"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
  end
end
