# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SprSims < Formula
  desc "Stacked Pull Requests on GitHub"
  homepage "https://github.com/MichaelSims/spr"
  version "2.0.0-sims"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MichaelSims/spr/releases/download/v2.0.0-sims/spr_macos_x86_64.tar.gz"
      sha256 "c1c743506ca3d2df7104bff3603c94426ec5f9b8ab8d85e1a2c1a910515ee7b9"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MichaelSims/spr/releases/download/v2.0.0-sims/spr_macos_arm64.tar.gz"
      sha256 "5bbb2e74635553f5b11371d1f0d3ce09cab317e1e02166edec7464e805e64b8d"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MichaelSims/spr/releases/download/v2.0.0-sims/spr_linux_arm64.tar.gz"
      sha256 "aec2503ea2558c3d815bf36c697eda6c84244968aa45a84aac82041fd5c5be38"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/MichaelSims/spr/releases/download/v2.0.0-sims/spr_linux_x86_64.tar.gz"
      sha256 "95c7982970b8226e4cbffede427ca5e441727aa85d4abab25cc8fd010c5b08ab"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
  end
end
