# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SprSims < Formula
  desc "Stacked Pull Requests on GitHub"
  homepage "https://github.com/MichaelSims/spr"
  version "1.0.0-sims"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/MichaelSims/spr/releases/download/v1.0.0-sims/spr_macos_arm64.tar.gz"
      sha256 "50391e4a4b65309ebf11d76748afa6a521472e1485dc2127b00202efe102fcf7"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/MichaelSims/spr/releases/download/v1.0.0-sims/spr_macos_x86_64.tar.gz"
      sha256 "74af7611900876c3a85ac9527a23c3f2857cae62eac09a9cbcfd627fe3ad53ff"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MichaelSims/spr/releases/download/v1.0.0-sims/spr_linux_arm64.tar.gz"
      sha256 "bd7494314317d391f3185dec63a2e607158b795283d59f7dc5880a1c77ed59e7"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/MichaelSims/spr/releases/download/v1.0.0-sims/spr_linux_x86_64.tar.gz"
      sha256 "c39646dce8363a41d6d4bb931d34e40bc05b6845ab8843811146fcc4dfa8dbbd"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
  end
end
